#1
print(length(d$Sex[d$Sex=='male']))
print(length(d$Sex[d$Sex=='female']))
#2
sd(d$Pclass)
sd(d[d$Sex=='male',]$Pclass)
sd(d[d$Sex=='female',]$Pclass)
dim(d[d$Sex=='male'&d$Pclass==2,])[1]
#3
round(median(d$Fare),2)
round(sd(d$Fare),2)
#4
ys=d[d$Age<30,]$Survived
print((y=length(ys[ys==1])/length(ys)))
os=d[d$Age>60,]$Survived
print((o=length(os[os==1])/length(os)))
y>o
#5
ms=d[d$Sex=='male',]$Survived
print((m=length(ms[ms==1])/length(ms)))
fs=d[d$Sex=='female',]$Survived
print((f=length(fs[fs==1])/length(fs)))
f>m
#6
getmode=function(v){
  u=unique(v)
  u[which.max(tabulate(match(v,u)))]
}
getmode(
  sapply(
    as.character(d[d$Sex=='male',]$Name),
    function(s){strsplit(s,',')[[1]][1]}
  )
)
#7
s=d[d$Survived==1,]
sai=which(!is.na(s$Age))
plot(s$Age,s$Fare,sub="survived")
ns=d[d$Survived==0,]
nsai=which(!is.na(ns$Age))
plot(ns$Age,ns$Fare,sub="not survived")
mean(s$Age[sai])<mean(ns$Age[nsai])
#8
mean(na.omit(d[d$Pclass==1&d$Sex=='male',]$Age))
mean(na.omit(d[d$Pclass==1&d$Sex=='female',]$Age))
mean(na.omit(d[d$Pclass==2&d$Sex=='male',]$Age))
mean(na.omit(d[d$Pclass==2&d$Sex=='female',]$Age))
mean(na.omit(d[d$Pclass==3&d$Sex=='male',]$Age))
mean(na.omit(d[d$Pclass==3&d$Sex=='female',]$Age))
